version: "3"

services:
    
    redis:
        container_name: redis
        image: redis:6-alpine

    api:
        container_name: api
        build:
            context: ./backend/api
            dockerfile: Dockerfile
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DEFAULT_REGION=us-west-2
            - S3_BUCKET_NAME=duxov.live
            - MUSIC_TABLE_NAME=duxov.live.music
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports: 
            - "8000:8000"
        volumes:
            - "./backend/api/app:/usr/src/app"
            - "./backend/api/tests:/usr/src/tests"
        command: uvicorn app.main:app --host 0.0.0.0 --reload